name = "apcs25/day_3"
version = "0.0.0"
compiler = "v1.1.15"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'apcs25/day_3'"

[repository]
user = "apcs25"
project = "day_3"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.2.0"
source = "github"

[config.default]
fee = 5000000

[config.mainnet]
fee = 10000000
